### ISSUE TITLE
Test plugin does not map correctly

### ISSUE THREAD

**Issue by Esophose** [jpenilla/special-gradle#1]
The test plugin does not seem to be mapping correctly. Stacktrace: https://pastebin.com/qJFiXsU9

I've tried using the special-gradle plugin on my own Spigot plugin, some things get mapped properly and others don't. It seems to struggle with cases where there are method overloads or instance variables of the same type with different generic parameters. Here are a couple examples I've noticed fail:

Attempting to access `Registry.ENTITY_TYPE` ends up getting remapped to an entirely different registry. Relevant stacktrace: https://pastebin.com/Gcic4p7j

Attempting to call `PlayerConnection#send(Packet)` ends up remapping to an overload of `PlayerConnection#send(Packet, GenericFutureListener)`, possibly due to the same name. `PlayerConnection#send` uses the name `send` when obfuscated, but `PlayerConnection#send(Packet, GenericFutureListener)` is named `a` instead. Relevant stacktrace: https://pastebin.com/etKwct6k

I was unsure if this was an issue with the special-gradle plugin or one with SpecialSource/the mappings instead. I decided to report here first, but if it ends up being an issue with SpecialSource or the mappings I'll remake the ticket on the proper repository. Thanks.

**Comment by jpenilla** [comment]
This is indeed an issue with SpecialSource. All Special Gradle really does is automate downloading and running SpecialSource for you.

**Comment by Esophose** [comment]
This possibly *is* an issue related to the Special Gradle plugin. I tried using the same test plugin's code using Special Gradle and md_5's SpecialSource plugin with Maven. The Maven one works fine, but the Gradle one fails to remap everything properly. 
Repository with examples: https://github.com/Esophose/MojangRemapTests
