### ISSUE TITLE
Could not find jackson-module-kotlin (for special-gradle)

### ISSUE THREAD

**Issue by Dymeth** [jpenilla/special-gradle#4]
Hello! I am getting this error when trying to connect special-gradle. How should I specify the repository to download this dependency? 

```
> Could not find com.fasterxml.jackson.module:jackson-module-kotlin:2.12.3.
     Searched in the following locations:
       - https://repo.jpenilla.xyz/snapshots/com/fasterxml/jackson/module/jackson-module-kotlin/2.12.3/jackson-module-kotlin-2.12.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :TestProject > xyz.jpenilla.special-gradle:xyz.jpenilla.special-gradle.gradle.plugin:1.0.0-SNAPSHOT:20210618.222045-4 > xyz.jpenilla:special-gradle:1.0.0-SNAPSHOT:20210618.222045-4
```

**Comment by jpenilla** [comment]
I would need to see your `settings.gradle.kts` to say for sure, but if you copied from the readme, it's missing `gradlePluginPortal()` in the `pluginManagement.repositories` block

**Comment by Dymeth** [comment]
> I would need to see your `settings.gradle.kts` to say for sure, but if you copied from the readme, it's missing `gradlePluginPortal()` in the `pluginManagement.repositories` block

gradlePluginPortal() solved my problem, thanks.
I actually used ReadMe. Perhaps it should be supplemented?
