### ISSUE TITLE
buildTools Gradle Task Fails when Minecraft Version is set to 1.18

### ISSUE THREAD

**Issue by DavidBerdik** [jpenilla/special-gradle#5]
Hello,

Starting with 1.17, I started using this plugin to build my plugin, and now, the time has come to update my plugin to 1.18. Unfortunately, I am having a problem that is preventing me from being able to do so. Whenever I try to use the `buildTools` task with the Minecraft version set to 1.18, the task fails. Here is an excerpt of the error message. I should note that the Spigot jar itself does appear to get built properly by BuildTools.

```
Success! Everything completed successfully. Copying final .jar files now.
Copying spigot-1.18-R0.1-SNAPSHOT-bootstrap.jar to C:\Users\David\.gradle\caches\special-gradle\buildtools\work\1.18\.\spigot-1.18.jar
  - Saved as .\spigot-1.18.jar

> Task :buildTools FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildTools'.
> kotlin.io.NoSuchFileException: C:\Users\David\.gradle\caches\special-gradle\buildtools\work\1.18\work\bukkit-8e9479b6-combined.csrg: The source file doesn't exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16m 22s
3 actionable tasks: 3 executed
```

Thanks in advance for your help!

**Comment by DavidBerdik** [comment]
Looking in to this issue more, I believe [this](https://github.com/jpenilla/special-gradle/blob/37bc0658d4c4432dbc5247095f55e343afdd1cb2/plugin/src/main/kotlin/xyz/jpenilla/specialgradle/task/BuildTools.kt#L130) to be the source of the trouble.

To resolve this, I think the most sensible solution would be to use the CSRG files that get dropped in the Maven cache of the user's home directory as described at the bottom of [this post](https://www.spigotmc.org/threads/9-years-of-spigotmc-spigot-bungeecord-1-18-release.534760/#post-4305163).

**Comment by jpenilla** [comment]
There are are variety of reasons special-gradle made the decision to bypass maven and directly use the buildtools cache, I would prefer generating the combined mappings in special gradle from the bukkit class mappings and member mappings generated by build tools (for those same reasons). This could be done quite easily using lorenz.

I do have some local changes which partially implement this, but I should let you know, I also plan to add the following warning:
```kotlin
    val warn = listOf(
      "",
      "***********************************************************************",
      "*                                                                     *",
      "*                              WARNING!                               *",
      "*                                                                     *",
      "*   Special Gradle is a toy project, not intended for serious use.    *",
      "*   It is encouraged to instead use 'paperweight-userdev'.            *",
      "*                                                                     *",
      "***********************************************************************",
      "",
    )
    warn.forEach { target.logger.lifecycle(it) }
```

See https://github.com/jpenilla/paperweight-test-plugin for a basic usage test/example

edit: it seems like some of the issues in BuildTools which forced this design may have changed, so if I were to properly update special-gradle a restructure may be possible around that, but again I now work on paperweight-userdev, which is far superior to special gradle, so I have no reason to

**Comment by DavidBerdik** [comment]
Awesome! Thank you! I had heard around the time that 1.17 came out that the Paper team had plans to develop a Gradle plugin to work with Spigot's SpecialSource tool, but at the time, I hadn't seen anything official about it. Since this is apparently the proper way to go about it now, I will work on migrating to paperweight-userdev. With that in mind, I suppose that this ticket can be closed, but I will leave that decision to you. Thanks again for the help!
